// USER STARTS
export const GET_USER = 'GET_USER';
export const USER_LOGIN = 'USER_LOGIN';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOADING = 'LOADING';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';

// USER ENDS

// POST STARTS
export const POST_ERROR = 'POST_ERROR';
export const POST_LOADING = 'POST_LOADING';
export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const GET_POST_BY_SLUG = 'GET_POST_BY_SLUG';
export const GET_MY_POSTS = 'GET_MY_POSTS';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';
// POST ENDS

// POST COMMENT STARTS
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
// POST COMMENT ENDS

// PROFILE STARTS
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_POSTS = 'FETCH_PROFILE_POSTS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
// PROFILE ENDS

export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

export const GET_TIMELINE_POSTS = 'GET_TIMELINE_POSTS';
